import type { Metadata } from "next";
import { DM_Sans, Space_Grotesk } from 'next/font/google';
import './globals.css';
import { AppProviders } from './provider';
import clsx from 'clsx';

const dmSans = DM_Sans({
  variable: '--font-dm-sans',
  subsets: ['latin'],
});

const spaceGrotesk = Space_Grotesk({
  variable: '--font-space-grotesk',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className={`${dmSans.variable} ${spaceGrotesk.variable} h-full antialiased`}
    >
      <body
        className={clsx(dmSans.className, 'min-h-dvh flex flex-col py-16 px-8')}
      >
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  );
}
